spring:
  application:
    name: service-consumer
  cloud:
    sentinel:
      datasource:
        ds1:
          file:
            file: classpath:sentinel-block-handler-flow.json
            rule-type: flow
            #rule-type: degrade
server:
  port: 8080


eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://Hins:Hins2021@127.0.0.1:1111/eureka,http://Hins:Hins2021@127.0.0.1:1112/eureka

logging:
  level:
    com.netflix: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
resttemplate:
  sentinel:
    enabled: true
feign:
  sentinel:
    enabled: true
